sonar.projectKey=Eco-Alerta
sonar.projectName=Eco-Alerta
sonar.projectVersion=1.0

# Código fuente a analizar
sonar.sources=backend,frontend/src

# Exclusiones
sonar.exclusions=**/node_modules/**,**/venv/**,**/venv_new/**,**/__pycache__/**,**/migrations/**,**/dist/**

# Configuración del servidor SonarQube
sonar.host.url=http://localhost:9000
sonar.token=sqa_28ca632a73a85c348a0c9b5a1c2d60aa9a1610ad

# Lenguajes
sonar.python.version=3.11
