# Generated by Django 6.0 on 2025-12-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportes", "0003_add_ubicacion_lat_lng"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reporte",
            name="ubicacion_lat",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="reporte",
            name="ubicacion_lng",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="reporte",
            index=models.Index(
                fields=["estado", "fecha_creacion"], name="reporte_estado_fecha_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reporte",
            index=models.Index(
                fields=["categoria", "estado"], name="reporte_categoria_estado_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reporte",
            index=models.Index(
                fields=["ubicacion_lat", "ubicacion_lng"], name="reporte_ubicacion_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reporte",
            index=models.Index(
                fields=["asignado_a", "estado"], name="reporte_asignado_estado_idx"
            ),
        ),
    ]
