# Generated by Django 5.2.9 on 2025-12-24 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportes", "0004_alter_reporte_ubicacion_lat_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusquedaGuardada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("parametros", models.JSONField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_ultimo_uso", models.DateTimeField(auto_now=True)),
                ("veces_usado", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Búsqueda Guardada",
                "verbose_name_plural": "Búsquedas Guardadas",
                "ordering": ["-fecha_ultimo_uso"],
            },
        ),
        migrations.CreateModel(
            name="ComentarioPublico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("comentario", models.TextField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("moderado", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Comentario Público",
                "verbose_name_plural": "Comentarios Públicos",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="HistorialCambio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_cambio",
                    models.CharField(
                        choices=[
                            ("estado", "Cambio de Estado"),
                            ("asignacion", "Asignación"),
                            ("notas", "Notas Internas"),
                            ("prioridad", "Prioridad"),
                            ("tags", "Tags"),
                            ("ubicacion", "Ubicación"),
                            ("categoria", "Categoría"),
                            ("descripcion", "Descripción"),
                        ],
                        max_length=20,
                    ),
                ),
                ("valor_anterior", models.TextField(blank=True, null=True)),
                ("valor_nuevo", models.TextField(blank=True, null=True)),
                ("fecha_cambio", models.DateTimeField(auto_now_add=True)),
                ("notas", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Historial de Cambio",
                "verbose_name_plural": "Historial de Cambios",
                "ordering": ["-fecha_cambio"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
                ("color", models.CharField(default="#3498db", max_length=7)),
                ("descripcion", models.TextField(blank=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["nombre"],
            },
        ),
        # Eliminar índices antiguos si existen (usando DROP INDEX IF EXISTS)
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS reporte_estado_fecha_idx;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS reporte_categoria_estado_idx;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS reporte_ubicacion_idx;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS reporte_asignado_estado_idx;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddIndex(
            model_name="reporte",
            index=models.Index(
                fields=["estado", "fecha_creacion"], name="rpt_estado_fecha_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reporte",
            index=models.Index(
                fields=["categoria", "estado"], name="rpt_cat_estado_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reporte",
            index=models.Index(
                fields=["ubicacion_lat", "ubicacion_lng"], name="rpt_ubicacion_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reporte",
            index=models.Index(
                fields=["asignado_a", "estado"], name="rpt_asig_estado_idx"
            ),
        ),
        migrations.AddField(
            model_name="reporte",
            name="direccion_completa",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="reporte",
            name="es_spam",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reporte",
            name="fecha_limite_resolucion",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reporte",
            name="fecha_validacion",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reporte",
            name="prioridad",
            field=models.CharField(
                choices=[
                    ("baja", "Baja"),
                    ("normal", "Normal"),
                    ("alta", "Alta"),
                    ("urgente", "Urgente"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="reporte",
            name="prioridad_calculada",
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name="reporte",
            name="score_confianza",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="reporte",
            name="tiempo_resolucion_horas",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reporte",
            name="validado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reporte",
            name="validado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reportes_validados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="busquedaguardada",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="busquedas_guardadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comentariopublico",
            name="reporte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comentarios_publicos",
                to="reportes.reporte",
            ),
        ),
        migrations.AddField(
            model_name="historialcambio",
            name="reporte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historial",
                to="reportes.reporte",
            ),
        ),
        migrations.AddField(
            model_name="historialcambio",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cambios_realizados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reporte",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="reportes", to="reportes.tag"
            ),
        ),
        migrations.AddIndex(
            model_name="reporte",
            index=models.Index(
                fields=["prioridad"], name="reportes_re_priorid_b6ebb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reporte",
            index=models.Index(
                fields=["prioridad_calculada"], name="reportes_re_priorid_df44ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reporte",
            index=models.Index(
                fields=["es_spam"], name="reportes_re_es_spam_9e1389_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reporte",
            index=models.Index(
                fields=["validado"], name="reportes_re_validad_82bc9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reporte",
            index=models.Index(
                fields=["prioridad_calculada", "estado"], name="rpt_prio_estado_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reporte",
            index=models.Index(
                fields=["asignado_a", "estado", "prioridad_calculada"],
                name="rpt_asig_est_prio_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="historialcambio",
            index=models.Index(
                fields=["reporte", "-fecha_cambio"],
                name="reportes_hi_reporte_794317_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="historialcambio",
            index=models.Index(
                fields=["tipo_cambio", "-fecha_cambio"],
                name="reportes_hi_tipo_ca_d2a6e4_idx",
            ),
        ),
    ]
