# Generated by Django 5.2.9 on 2026-01-19 15:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reportes",
            "0005_busquedaguardada_comentariopublico_historialcambio_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="reporte",
            name="reporte_estado_fecha_idx",
        ),
        migrations.RemoveIndex(
            model_name="reporte",
            name="reporte_categoria_estado_idx",
        ),
        migrations.RemoveIndex(
            model_name="reporte",
            name="reporte_ubicacion_idx",
        ),
        migrations.RemoveIndex(
            model_name="reporte",
            name="reporte_asignado_estado_idx",
        ),
        migrations.RemoveIndex(
            model_name="reporte",
            name="rpt_ubicacion_idx",
        ),
        migrations.RemoveField(
            model_name="reporte",
            name="ubicacion_lat",
        ),
        migrations.RemoveField(
            model_name="reporte",
            name="ubicacion_lng",
        ),
        migrations.AddField(
            model_name="reporte",
            name="ubicacion",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="historialcambio",
            name="tipo_cambio",
            field=models.CharField(
                choices=[
                    ("estado", "Cambio de Estado"),
                    ("asignacion", "Asignación"),
                    ("notas", "Notas Internas"),
                    ("prioridad", "Prioridad"),
                    ("tags", "Tags"),
                    ("ubicacion", "Ubicación"),
                    ("categoria", "Categoría"),
                    ("descripcion", "Descripción"),
                    ("validacion", "Validación"),
                ],
                max_length=20,
            ),
        ),
    ]
