# Generated by Django 5.2.9 on 2026-01-19 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportes", "0006_remove_reporte_reporte_estado_fecha_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReporteImagen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagen", models.ImageField(upload_to="reportes_galeria/")),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "reporte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes",
                        to="reportes.reporte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagen de Reporte",
                "verbose_name_plural": "Imágenes de Reporte",
            },
        ),
    ]
