# Generated by Django 5.2.9 on 2026-02-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0007_reporteimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='validaciones_ciudadanas',
            field=models.IntegerField(default=0),
        ),
    ]
