# Generated by Django 5.2.9 on 2026-02-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportes", "0008_reporte_validaciones_ciudadanas"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="fecha_actualizacion_ubicacion",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="ubicacion_actual_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="ubicacion_actual_lng",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
