# Generated by Django 5.2.9 on 2026-02-20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0009_usuario_fecha_actualizacion_ubicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='sla_escalado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reporte',
            name='sla_escalado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='sla_ultima_alerta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CierreReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidencia_texto', models.TextField(blank=True)),
                ('foto_cierre', models.ImageField(blank=True, null=True, upload_to='reportes_cierre/')),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_registrados', to=settings.AUTH_USER_MODEL)),
                ('reporte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cierre', to='reportes.reporte')),
            ],
            options={
                'verbose_name': 'Cierre de Reporte',
                'verbose_name_plural': 'Cierres de Reportes',
            },
        ),
    ]
