# Generated by Django 5.2.9 on 2026-03-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportes", "0010_reportesla_cierre"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="tour_completado",
            field=models.BooleanField(default=False),
        ),
    ]
