# Generated by Django 5.2.9 on 2026-03-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0012_historicalreporte_historicalusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreporte',
            name='ai_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='ai_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
