# Generated by Django 5.2.9 on 2026-08-13 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportes", "0013_historicalreporte_ai_metadata_reporte_ai_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartamentoMunicipal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True)),
                ("email_contacto", models.EmailField(blank=True, max_length=254)),
                ("telefono", models.CharField(blank=True, max_length=30)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Departamento Municipal",
                "verbose_name_plural": "Departamentos Municipales",
                "ordering": ["nombre"],
            },
        ),
        migrations.AlterField(
            model_name="reporte",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reportes",
                to="reportes.categoriaresiduo",
            ),
        ),
        migrations.CreateModel(
            name="CapaUrbana",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("icono", models.CharField(default="map", max_length=50)),
                ("color_hex", models.CharField(default="#3498db", max_length=7)),
                ("activa", models.BooleanField(default=True)),
                ("orden", models.IntegerField(default=0)),
                (
                    "departamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="capas",
                        to="reportes.departamentomunicipal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Capa Urbana",
                "verbose_name_plural": "Capas Urbanas",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="SubcategoriaUrbana",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                ("icono", models.CharField(blank=True, max_length=50)),
                ("sla_horas", models.IntegerField(default=72)),
                (
                    "prioridad_base",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("normal", "Normal"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                ("orden", models.IntegerField(default=0)),
                (
                    "capa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategorias",
                        to="reportes.capaurbana",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subcategoría Urbana",
                "verbose_name_plural": "Subcategorías Urbanas",
                "ordering": ["capa__orden", "orden", "nombre"],
            },
        ),
        migrations.AddField(
            model_name="historicalreporte",
            name="subcategoria",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="reportes.subcategoriaurbana",
            ),
        ),
        migrations.AddField(
            model_name="reporte",
            name="subcategoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reportes",
                to="reportes.subcategoriaurbana",
            ),
        ),
    ]
