# Generated by Django 5.2.9 on 2026-08-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportes", "0016_add_rag_embedding"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionMunicipio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(default="Mi Municipio", max_length=150)),
                ("region", models.CharField(blank=True, default="", max_length=100)),
                ("pais", models.CharField(default="Chile", max_length=60)),
                ("mapa_lat", models.FloatField(default=-29.9027)),
                ("mapa_lng", models.FloatField(default=-71.252)),
                ("mapa_zoom", models.IntegerField(default=13)),
                ("bounds_norte", models.FloatField(blank=True, null=True)),
                ("bounds_sur", models.FloatField(blank=True, null=True)),
                ("bounds_este", models.FloatField(blank=True, null=True)),
                ("bounds_oeste", models.FloatField(blank=True, null=True)),
                ("logo_url", models.URLField(blank=True, default="")),
                ("color_primario", models.CharField(default="#1a6b3c", max_length=7)),
                ("color_secundario", models.CharField(default="#2d9e5f", max_length=7)),
                (
                    "email_contacto",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "telefono_contacto",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("sitio_web", models.URLField(blank=True, default="")),
                (
                    "direccion_municipio",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "slogan",
                    models.CharField(
                        blank=True,
                        default="Sistema de Reportes Ciudadanos Urbanos",
                        max_length=200,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración del Municipio",
                "verbose_name_plural": "Configuración del Municipio",
            },
        ),
    ]
